from common import *
# ---------- Paper II ----------
hi = N("A. History and Culture of India", [
 unit("1. Pre-Historic Cultures to the Guptas and the Kanauj", 15, 8, "1. Pre-Historic Cultures in India- Indus Valley Civilization- Vedic Culture- Mahajanapadas- Emergence of New Religions- Jainism, Buddhism- Rise of the Magadha and Age of the Mauryas- Ashoka Dharma- Foreign Invasions on India- The Kushans.",
  ["Pre-Historic Cultures in India", "Indus Valley Civilization", "Vedic Culture", "Mahajanapadas", "Emergence of New Religions- Jainism, Buddhism",
   "Rise of the Magadha and Age of the Mauryas- Ashoka Dharma", "Foreign Invasions on India- The Kushans", "The Satavahanas, the Sangam Age in South India- the Sungas- the Guptas",
   "the Kanauj and their Contributions- Historical Accounts of Foreign travelers- Early Educational Institutions"]),
 unit("2. The Pallavas to the Vijayanagaras: dynasties, Sultanates and religious movements", 15, 8, "2. The Pallavas, the Badami Chalukyas, the Eastern Chalukyas, the Rashtrakutas, the Kalyani Chalukyas and the Cholas- Socio Cultural Contributions, Language, Literature Art and Architecture- Delhi Sultanates- Advent of Islam and its Impact- Religious Movements like Bhakti and Sufi and Its Influence.",
  ["The Pallavas, the Badami Chalukyas, the Eastern Chalukyas, the Rashtrakutas, the Kalyani Chalukyas and the Cholas- Socio Cultural Contributions, Language, Literature Art and Architecture",
   "Delhi Sultanates- Advent of Islam and its Impact", "Religious Movements like Bhakti and Sufi and Its Influence", "Growth of Vernacular Languages, Scripts, Literature, Fine Arts",
   "Socio Cultural Conditions of the Kakatiyas, the Vijayanagaras, the Bahmanis, the Qutubsahis and their cotemporary South Indian kingdoms"]),
 unit("3. The Mughals, Marathas and the Advent of Europeans", 15, 8, "3. The Mughals Administration, Socio-Religious life and Cultural developments- Shivaji and Rise of Maratha Empire- Advent of Europeans in India.",
  ["The Mughals Administration, Socio-Religious life and Cultural developments", "Shivaji and Rise of Maratha Empire", "Advent of Europeans in India",
   "Trade practices- Rise of East India Company its Hegemony", "Changes in Administration, Social and Cultural spheres- Role of Christian Missionaries"]),
 unit("4. British rule, 1857 and the rise of Indian nationalism", 15, 9, "4. Rise of British rule in India from 1757 to 1856- Land Revenue Settlement, Permanent Settlement, Ryothvari and Mahalvari- 1857 Revolt and its Impact-Education, Press, Cultural changes- Rise of National Consciousness and Changes- Socio-Religious Reform Movements in 19th century- Rajaram Mohan Roy, Dayananda Saraswathi, Swamy Vivekananda, Annie Besant, Sir Syed Ahmad Khan and others.",
  ["Rise of British rule in India from 1757 to 1856", "Land Revenue Settlement, Permanent Settlement, Ryothvari and Mahalvari", "1857 Revolt and its Impact", "Education, Press, Cultural changes",
   "Rise of National Consciousness and Changes", "Socio-Religious Reform Movements in 19th century- Rajaram Mohan Roy, Dayananda Saraswathi, Swamy Vivekananda, Annie Besant, Sir Syed Ahmad Khan and others",
   "Rise of Indian Nationalism- Activities of Indian National Congress- Vandemataram, Home Rule Movements- Self Respect Movement",
   ("Jyothiba Phule, Narayana Guru, Periyar Ramaswamy Naicker", 1.5, 16), ("Role of Mahatma Gandhi, Subhash Chandra Bose, Vallabai Patel- Satyagraha- Quit India Movement", 2.5, 16),
   ("Dr B.R. Ambedkar and his Contributions", 2, 16)]),
 unit("5. Freedom struggle phases, Independence and after", 16, 9, "5. Indian Nationalism in three phases- Freedom Struggle 1885-1905, 1905-1920 and Gandhi Phase 1920-1947- Peasant, Women, Tribal and Workers Movements- Role of Different parties in Freedom Struggle- Local and Regional Movements- Inter Religious Unity and Communalism.",
  ["Indian Nationalism in three phases- Freedom Struggle 1885-1905, 1905-1920 and Gandhi Phase 1920-1947", "Peasant, Women, Tribal and Workers Movements", "Role of Different parties in Freedom Struggle",
   "Local and Regional Movements", "Inter Religious Unity and Communalism", "Independence and Partition of India", "India after Independence- Rehabilitation after partition",
   "Linguistic Re-organization of States- Integration of the Indian States", "Indian Constitution- Economic policies- Foreign Policy Initiatives"]),
], imp=8, page=15, extra=[("A .History and Culture of India:", 15)])

ha = N("B. History and Culture of Andhra Pradesh", [
 unit("6. Ancient Andhra", 16, 9, "6. Ancient: The Satavahanas, the Ikshvukus, the Salankayanas, the Pallavas and the Vishnukundins- Social and Economic Conditions- Religion, Language (Telugu), Literature, Art and Architecture- Jainism and Buddhism in Andhra.",
  ["The Satavahanas, the Ikshvukus, the Salankayanas, the Pallavas and the Vishnukundins", "Social and Economic Conditions- Religion, Language (Telugu), Literature, Art and Architecture", "Jainism and Buddhism in Andhra",
   "The Eastern Chalukyas, the Rashtrakutas, the Renati Cholas and others", "Socio-Cultural life, Religion- Telugu Script and Language, Literature, Art and Architecture"]),
 unit("7. Medieval Andhra", 16, 10, "7. Medieval: Socio- Cultural and Religious Conditions in Andhradesa 1000 to 1565 A.D.-Antiquity, Origin and Growth Telugu Language and Literature (Kavitraya- Asthadiggajas)- Fine Arts, Art& Architecture during the reign of Kakatiyas, Reddis, Gajapatis and Vijayanagaras and their feudatories.",
  ["Socio- Cultural and Religious Conditions in Andhradesa 1000 to 1565 A.D.", "Antiquity, Origin and Growth Telugu Language and Literature (Kavitraya- Asthadiggajas)",
   "Fine Arts, Art& Architecture during the reign of Kakatiyas, Reddis, Gajapatis and Vijayanagaras and their feudatories", "Historical Monuments-Significance",
   "Contribution of Qutubshahis to Andhra History and Culture", "Regional Literature- Praja Kavi -Vemana and others"]),
 unit("8. Modern Andhra", 16, 10, "8. Modern: European Trade Establishments in Andhra- Andhra Under the Company Rule- Role of Christian Missionaries- Socio-Cultural, Literary Awakening- C.P. Brown, Thamos Munro, Mackenzie-Zamindary, Polegary System- Native States and Little Kings.",
  ["European Trade Establishments in Andhra", "Andhra Under the Company Rule", "Role of Christian Missionaries", "Socio-Cultural, Literary Awakening- C.P. Brown, Thamos Munro, Mackenzie",
   "Zamindary, Polegary System- Native States and Little Kings",
   "Role of Social Reformers- Gurajada Apparao, Kandukuri Veeresalingam, Raghupati Venkataratnam Naidu, Gidugu Ramamurthy, Annie Besant and others",
   "Library Movement in Andhra Pradesh- Role of News Paper", ("Folk and Tribal Culture, Oral Traditions, Subaltern Culture, Role of women", 2, 17)]),
 unit("9. Nationalist Movement and the formation of Andhra Pradesh", 17, 10, "9. Nationalist Movement: Role of Andhra leaders- Justice Party, Non-Brahmin Movement- Nationalist and Revolutionary Literature- Gurram Jashva, Boyi Bheemanna, Sri Sri, Garimella Satyanarayana, Rayaprolu Subbarao, Unnava Lakshminarayana, Tripuraneni Ramaswamy Choudhary and others,",
  ["Role of Andhra leaders- Justice Party, Non-Brahmin Movement",
   "Nationalist and Revolutionary Literature- Gurram Jashva, Boyi Bheemanna, Sri Sri, Garimella Satyanarayana, Rayaprolu Subbarao, Unnava Lakshminarayana, Tripuraneni Ramaswamy Choudhary and others",
   "Andhra Mahasabhas, Andhra Movement- prominent leaders- Alluri Sitaramraju, Duggirala Gopalakrishnaiah, Konda Venkatappayya, Pattabhi Seetaramaiah",
   "Ponaka Kanakamma, Dokka Sitamma- Grandhlaya Movement- Ayyanka Venkataratnam, Gadicherla Harisarvothamarao, Kasinanathuni Nagesvara Rao- Potti Sreeramulu",
   "Formation of Andhra State,1953", "Emergence of Andhra Pradesh,1956", "Andhra Pradesh 1956 to2014- Causes for Bifurcation, 2nd June 2014 Impact"], h=2),
 unit("10. Andhra Pradesh: bifurcation and its impact", 17, 10, "10. Andhra Pradesh: Bifurcation of Andhra Pradesh and its impact on Administrative, Economic, Social, Political, Cultural and Legal Implications- Loss of Capital City, Building of New Capital and its financial Implications- Division of Employees and their Native Issues- Effect of Bifurcation on Trade& Commerce, Industry – Implication of Financial Resources of State Government.",
  ["Bifurcation of Andhra Pradesh and its impact on Administrative, Economic, Social, Political, Cultural and Legal Implications", "Loss of Capital City, Building of New Capital and its financial Implications",
   "Division of Employees and their Native Issues", "Effect of Bifurcation on Trade& Commerce, Industry – Implication of Financial Resources of State Government",
   "Developmental Opportunities- Socio-Economic, Cultural and Demographic impact of Bifurcation", "Impact on River water sharing and other link issues",
   "Andhra Pradesh Reorganization Act.2014- the Arbitrariness of certain provisions"], h=2),
], imp=10, page=16, extra=[("B .History and Culture of Andhra Pradesh:", 16)])

ge = N("C. Geography: India and Andhra Pradesh", [
 unit("11. Physical Features and Resources", 17, 8, "11. Physical Features and Resources: India and Andhra Pradesh, Major land forms, Climatic changes, Soil types, Rivers, Water, Streams, Geology, Rocks, Mineral Resources, Metals, Clays, Construction Materials, Reservoirs, Dams — Forests, Mountains, Hills, Flora and fauna, Plateau Forests, Hill Forests, Vegetation Classification.",
  ["Physical Features and Resources: India and Andhra Pradesh, Major land forms, Climatic changes, Soil types", "Rivers, Water, Streams", "Geology, Rocks, Mineral Resources, Metals, Clays, Construction Materials",
   "Reservoirs, Dams", "Forests, Mountains, Hills, Flora and fauna, Plateau Forests, Hill Forests, Vegetation Classification"]),
 unit("12. Economic Geography", 17, 8, "12. Economic Geography : Agriculture, Live stocks, Forestry, Fishery, Quarrying, Mining, House hold Manufacturing, Industries — Agro, Mineral, Forest, Fuel and man power, Trade and Commerce, Communication, Road Transport, Storage and others.",
  ["Economic Geography : Agriculture, Live stocks, Forestry, Fishery", "Quarrying, Mining, House hold Manufacturing", "Industries — Agro, Mineral, Forest, Fuel and man power", "Trade and Commerce, Communication, Road Transport, Storage and others"]),
 unit("13. Social Geography", 17, 7, "13. Social Geography: Population Movements and Distribution, Human Habitations, Density, Age, Sex, Rural, Urban, Race, Caste, Tribe, Religion, Linguistic, Urban Migration, Education Characteristics.",
  ["Social Geography: Population Movements and Distribution", "Human Habitations, Density, Age, Sex, Rural, Urban", ("Race, Caste, Tribe, Religion, Linguistic", 1.5, 18), ("Urban Migration", 1, 18), ("Education Characteristics", 1, 18)]),
 unit("14. Fauna and Floral Geography", 18, 7, "14. Fauna and Floral Geography: Wild Animals, Animals, Birds, Reptiles, Mammals, Trees and Plants and others.",
  ["Fauna and Floral Geography: Wild Animals, Animals, Birds, Reptiles, Mammals", "Trees and Plants and others"]),
 unit("15. Environmental Geography", 18, 8, "15. Environmental Geography: Sustainable Development, Globalization, Temperature, Humidity, Cloudiness, Winds, Special Weather Phenomena, Natural Hazards — Earth Quakes, Land Slides, Floods, Cyclones, Cloud Burst, Disaster Management, Impact Assessment, Environmental Pollution, Pollution Management.",
  ["Environmental Geography: Sustainable Development, Globalization", "Temperature, Humidity, Cloudiness, Winds, Special Weather Phenomena", "Natural Hazards — Earth Quakes, Land Slides, Floods, Cyclones, Cloud Burst",
   "Disaster Management, Impact Assessment", "Environmental Pollution, Pollution Management"]),
], imp=8, page=17, extra=[("C. Geography: India and Andhra Pradesh", 17)])

paper2 = N("Paper II - History, Culture and Geography of India and Andhra Pradesh (150)", [hi, ha, ge], imp=9, page=15,
  extra=[("Paper-II History and Cultural and Geography of India and Andhra Pradesh - 180 minutes - 150 Marks", 5),
         ("PAPER — II: HISTORY, CULTURE AND GEOGRAPHY OF INDIA AND ANDHRA PRADESH (DEGREE STANDARD) Marks — 150 Medium: English / Telugu Time- 180 Minutes", 15)])
