"""m3 to m12 tables

Revision ID: 0003
Revises: 0002
"""
import sqlalchemy as sa
from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('word_limit', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('image_paths', sa.JSON(), nullable=False),
    sa.Column('feedback_json', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_updated_at'), ['updated_at'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mcq_id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=True),
    sa.Column('chosen', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('mistake_type', sa.String(length=20), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_mcq_id'), ['mcq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_updated_at'), ['updated_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('via', sa.String(length=10), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_updated_at'), ['updated_at'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('topic_ids', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('compilations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compilations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compilations_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_compilations_updated_at'), ['updated_at'], unique=False)

    op.create_table('daily_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('blocks_json', sa.JSON(), nullable=False),
    sa.Column('completion_json', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_plans_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_plans_updated_at'), ['updated_at'], unique=False)

    op.create_table('doc_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doc_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_pages_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_pages_updated_at'), ['updated_at'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('status_detail', sa.String(length=300), nullable=False),
    sa.Column('reading_position', sa.JSON(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_updated_at'), ['updated_at'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_tentative', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_updated_at'), ['updated_at'], unique=False)

    op.create_table('explain_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('feedback_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('explain_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_explain_sessions_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_explain_sessions_updated_at'), ['updated_at'], unique=False)

    op.create_table('focus_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('block_id', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('completion_pct', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_sessions_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_updated_at'), ['updated_at'], unique=False)

    op.create_table('highlights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_highlights_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_highlights_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_highlights_updated_at'), ['updated_at'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_updated_at'), ['updated_at'], unique=False)

    op.create_table('library_list',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book', sa.String(length=200), nullable=False),
    sa.Column('why', sa.String(length=300), nullable=False),
    sa.Column('chapters', sa.JSON(), nullable=False),
    sa.Column('visit_date', sa.String(length=10), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_list_updated_at'), ['updated_at'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('why', sa.String(length=400), nullable=False),
    sa.Column('needed_for', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_updated_at'), ['updated_at'], unique=False)

    op.create_table('mcqs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcqs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcqs_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcqs_updated_at'), ['updated_at'], unique=False)

    op.create_table('mistakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mcq_id', sa.String(length=36), nullable=False),
    sa.Column('mistake_type', sa.String(length=20), nullable=False),
    sa.Column('your_answer', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mistakes_mcq_id'), ['mcq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_updated_at'), ['updated_at'], unique=False)

    op.create_table('note_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_versions_note_id'), ['note_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('owner_edited', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_updated_at'), ['updated_at'], unique=False)

    op.create_table('pyqs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('paper', sa.String(length=80), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer_index', sa.Integer(), nullable=False),
    sa.Column('topic_ids', sa.JSON(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pyqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pyqs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pyqs_updated_at'), ['updated_at'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_updated_at'), ['updated_at'], unique=False)

    op.create_table('revision_order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('group_order', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_order_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_order_updated_at'), ['updated_at'], unique=False)

    op.create_table('revision_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_rules_updated_at'), ['updated_at'], unique=False)

    op.create_table('sheets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('audio_path', sa.String(length=300), nullable=True),
    sa.Column('pdf_path', sa.String(length=300), nullable=True),
    sa.Column('audio_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheets_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sheets_updated_at'), ['updated_at'], unique=False)

    op.create_table('syllabus_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tree_json', sa.JSON(), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('syllabus_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_syllabus_imports_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_syllabus_imports_updated_at'), ['updated_at'], unique=False)

    op.create_table('telugu_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telugu_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telugu_items_updated_at'), ['updated_at'], unique=False)

    op.create_table('telugu_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telugu_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telugu_progress_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telugu_progress_updated_at'), ['updated_at'], unique=False)

    op.create_table('tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mcq_ids', sa.JSON(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('negative_marking', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tests_updated_at'), ['updated_at'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('syllabus_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('paper', sa.String(length=120), nullable=False),
    sa.Column('exam_tags', sa.JSON(), nullable=False),
    sa.Column('est_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_syllabus_id'), ['syllabus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_updated_at'), ['updated_at'], unique=False)

    op.create_table('video_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_notes_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_notes_video_id'), ['video_id'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('youtube_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('channel', sa.String(length=200), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('embeddable', sa.Boolean(), nullable=False),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_youtube_id'), ['youtube_id'], unique=False)

    op.create_table('weekly_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('audio_path', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_reports_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_reports_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_reports_week_start'))
        batch_op.drop_index(batch_op.f('ix_weekly_reports_updated_at'))

    op.drop_table('weekly_reports')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_youtube_id'))
        batch_op.drop_index(batch_op.f('ix_videos_updated_at'))
        batch_op.drop_index(batch_op.f('ix_videos_topic_id'))

    op.drop_table('videos')
    with op.batch_alter_table('video_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_notes_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_notes_updated_at'))

    op.drop_table('video_notes')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_updated_at'))
        batch_op.drop_index(batch_op.f('ix_topics_syllabus_id'))
        batch_op.drop_index(batch_op.f('ix_topics_parent_id'))

    op.drop_table('topics')
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_updated_at'))

    op.drop_table('tests')
    with op.batch_alter_table('telugu_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telugu_progress_updated_at'))
        batch_op.drop_index(batch_op.f('ix_telugu_progress_item_id'))

    op.drop_table('telugu_progress')
    with op.batch_alter_table('telugu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telugu_items_updated_at'))

    op.drop_table('telugu_items')
    with op.batch_alter_table('syllabus_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_syllabus_imports_updated_at'))
        batch_op.drop_index(batch_op.f('ix_syllabus_imports_document_id'))

    op.drop_table('syllabus_imports')
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheets_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sheets_topic_id'))

    op.drop_table('sheets')
    with op.batch_alter_table('revision_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_rules_updated_at'))

    op.drop_table('revision_rules')
    with op.batch_alter_table('revision_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_order_updated_at'))
        batch_op.drop_index(batch_op.f('ix_revision_order_date'))

    op.drop_table('revision_order')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_updated_at'))
        batch_op.drop_index(batch_op.f('ix_reviews_card_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('pyqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pyqs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_pyqs_document_id'))

    op.drop_table('pyqs')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notes_topic_id'))

    op.drop_table('notes')
    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_versions_note_id'))

    op.drop_table('note_versions')
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mistakes_updated_at'))
        batch_op.drop_index(batch_op.f('ix_mistakes_mcq_id'))

    op.drop_table('mistakes')
    with op.batch_alter_table('mcqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcqs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_mcqs_topic_id'))
        batch_op.drop_index(batch_op.f('ix_mcqs_source_id'))

    op.drop_table('mcqs')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_updated_at'))

    op.drop_table('materials')
    with op.batch_alter_table('library_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_list_updated_at'))

    op.drop_table('library_list')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_updated_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_highlights_updated_at'))
        batch_op.drop_index(batch_op.f('ix_highlights_topic_id'))
        batch_op.drop_index(batch_op.f('ix_highlights_document_id'))

    op.drop_table('highlights')
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_sessions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_topic_id'))

    op.drop_table('focus_sessions')
    with op.batch_alter_table('explain_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explain_sessions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_explain_sessions_topic_id'))

    op.drop_table('explain_sessions')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_updated_at'))

    op.drop_table('exams')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_updated_at'))
        batch_op.drop_index(batch_op.f('ix_documents_topic_id'))

    op.drop_table('documents')
    with op.batch_alter_table('doc_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doc_pages_updated_at'))
        batch_op.drop_index(batch_op.f('ix_doc_pages_document_id'))

    op.drop_table('doc_pages')
    with op.batch_alter_table('daily_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_plans_updated_at'))
        batch_op.drop_index(batch_op.f('ix_daily_plans_date'))

    op.drop_table('daily_plans')
    with op.batch_alter_table('compilations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compilations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_compilations_month'))

    op.drop_table('compilations')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_document_id'))

    op.drop_table('chunks')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_updated_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_attempts_test_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_mcq_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_updated_at'))
        batch_op.drop_index(batch_op.f('ix_answers_topic_id'))

    op.drop_table('answers')
    # ### end Alembic commands ###
